version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=unit
      - POSTGRES_DB=test-unit
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: